### ISSUE TITLE
ResultPage Bug

### ISSUE THREAD

**Issue by Jaideep-C** [Sahith182/flashorant#11]
While navigating to ResultPage from HomePage, without selecting any dropdown value, we can still navigate.
![image](https://user-images.githubusercontent.com/51963564/126611615-8a9a8f03-f9b9-4d87-a915-a71acbb179bc.png)

**Comment by sahith182** [comment]
I will solve the bug

**Comment by Jaideep-C** [comment]
Cool😊

**Comment by sahith182** [comment]
This issue is solved with [this](https://github.com/Sahith182/flashorant/commit/8c9e2ba5a2b068609ee835ecfe9d6419413d50c2) commit.
